language: java
#before_install:
#  - sudo chmod +x mvnw
jdk:
- openjdk8

branches:
only:
- master
  
# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

script: "mvn test -B"

before_deploy:
- zip -r tghr-springboot-webservice *
- mkdir -p deploy
- mv tghr-springboot-webservice.zip deploy/tghr-springboot-webservice.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
  bucket: tghrcontents # S3 버킷
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  local_dir: deploy # before_deploy에서 생성한 디렉토리
  wait-until-deployed: true
  on:
  repo: whitesj1030/tghr
  branch: master

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
  bucket: tghrcontents # S3 버킷
  key: tghr-springboot-webservice.zip # 빌드 파일을 압축해서 전달
  bundle_type: zip
  application: tghr-springboot-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
  deployment_group: tghr-springboot-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
  region: ap-northeast-2
  wait-until-deployed: true
  on:
  repo: whitesj1030/tghr #Github 주소
  branch: master

# CI 실행 완료시 메일로 알람
notifications:
email:
recipients:
- ycpopo@naver.com
