language: java
jdk:
- openjdk8

branches:
only:
- master

before_install:
  - chmod +x mvnw
  
# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

script: "mvn test -B"

# CI 실행 완료시 메일로 알람
notifications:
email:
recipients:
- ycpopo@naver.com